export enum EArmadaDiceSide {
  BLANK = 'BLANK',
  SINGLE_HIT = 'SINGLE_HIT',
  DOUBLE_HIT = 'DOUBLE_HIT',
  ACCURACY = 'ACCURACY',
  CRITICAL = 'CRITICAL',
  CRITICAL_AND_SINGLE_HIT = 'CRITICAL_AND_SINGLE_HIT',
}
